# Generated by Django 2.0.3 on 2018-03-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailoutuser',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emails.MailoutCategory'),
        ),
    ]
